### PR TITLE
Release Commit

### PR DESCRIPTION
**Pull request by batraabhishek**

### CODE REVIEW

**Comment by tradzik** [comment]
@batraabhishek Thank you! Can you take a look on currently open issues and handle them properly? It would be nice if you upload somewhere APK also. :+1:

**Comment by batraabhishek** [comment]
Sure :)

Please find apk here https://github.com/fossasia/fossasia-companion-android/releases/tag/0.9

**Comment by tradzik** [comment]
@batraabhishek Thank you :-) I am signing and publishing APK immediately

**Comment by tradzik** [comment]
@batraabhishek @mariobehling Application has been published. It should start being downloadable in Google Play in next few hours... Thank you for your work!

**Pull request merged**
