### PR TITLE
Changed fosdem image in navigation header to fossasia

### PR DESCRIPTION
**Pull request by mananwason**
device-2015-03-03-225058

### CODE REVIEW

**Comment by tradzik** [comment]
@mananwason Hi, thank you for your changes! They seem to be ok. I have one suggestion - can you remove old FOSDEM logo? We do not need having all unused assets.

**Comment by mananwason** [comment]
@ty221 I thought I removed it, anyways I'll do it by tomorrow.

**Comment by tradzik** [comment]
@mananwason Ok, I will merge your PR after you remove this old logo. Thanks for your edits and involvment in creating our app!

**Comment by mananwason** [comment]
Sure tymon :D

**Comment by mananwason** [comment]
@ty221 It's done, you may proceed with the merging. Thanks.

**Comment by tradzik** [comment]
@mananwason Thanks. Merged.

**Pull request merged**
