### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by todipratik**

### CODE REVIEW

**Comment by todipratik** [comment]
@mariobehling please see the about dialog and suggest necessary changes !

**Comment by todipratik** [comment]
@mariobehling please check the PR and suggest the changes, if any.

**Comment by tradzik** [comment]
@todipratik For me your changes are good, however it would be much better if @mariobehling wil tell something about them.

**Comment by todipratik** [comment]
@mariobehling Any comments from your side?

**Comment by mariobehling** [comment]
These changes are surely necessary. No need for me to get into details. It is great to see how you guys are working on this. From what I see, I have full confidence in your work. Thanks so much!

**Comment by mariobehling** [comment]
Im out on mobile. @everyone please merge your suggestions

**Comment by todipratik** [comment]
@ty221 Can it be merged now?

**Pull request merged**
